# 数据库的连接新
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.30.128:8848
    sentinel:
      transport:
        port: 8719
        dashboard: localhost:8080
        client-ip: localhost
  application:
    name: mall-seckill
  redis:
    host: 192.168.30.128
    port: 6380
    password: 1qaz@WSX
  task:
    execution:
      pool:
        core-size: 5
        max-size: 20
  session:
    store-type: redis
    redis:
      namespace: spring:redis
  thymeleaf:
    cache: false

server:
  port: 9601

# RocketMQ的相关信息
rocketmq:
  name-server: 192.168.30.128:9876
  producer:
    group: seckill-order-producer
  consumer:
    group: seckill-order-consumer
management:
  endpoints:
    web:
      exposure:
        include: '*'


