server:
  port: 8030
  servlet:
    session:
      timeout: 30m
## 数据库的连接新
spring:
  application:
    name: mall-order

  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.30.128:3308/mall-oms
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.30.128:8848
    #alibaba:
     # seata:
      #  tx-service-group: mall-order-group
    sentinel:
      transport:
        port: 8719
        client-ip: localhost
        dashboard: localhost:8080
  session:
    store-type: redis
    redis:
      namespace: spring:session
  redis:
    host: 192.168.30.128
    port: 6380
    password: 1qaz@WSX

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto # 主键自增

user:
  userName: zhangsan
  age: 18

# RocketMQ的相关信息
rocketmq:
  name-server: 192.168.30.128:9876
  producer:
    group: order-producer
  consumer:
    group: order-consumer
management:
  endpoints:
    web:
      exposure:
        include: '*'

